# Generated by Django 2.1.1 on 2018-09-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='machine_ip',
        ),
    ]
